TAREA 2/GRUPO6/tarea/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('/producto', 'Productocontroller');

TAREA 2/GRUPO6/tarea/app/Producto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Producto extends Model
{
    protected $fillable = ['nombre', 'precio', 'descripcion'];
}

TAREA 2/GRUPO6/tarea/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

TAREA 2/GRUPO6/tarea/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

TAREA 2/GRUPO6/tarea/app/Http/Controllers/ProductoController.php
<?php

namespace App\Http\Controllers;

use App\Producto;
use Illuminate\Http\Request;

class ProductoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //select * from productos where 1
        $productos = Producto::all();
        return view('productos.index', compact('productos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('productos.create');        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Producto::create($request->all());
        return redirect()->route('producto.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Producto  $producto
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $producto = Producto::findOrFail($id);
        return view('productos.show', compact('producto'));        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Producto  $producto
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $producto = Producto::findOrFail($id);
        return view('productos.edit', compact('producto'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Producto  $producto
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $producto = Producto::findOrFail($id);
        $producto->update($request->all());
        return redirect()->route('producto.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Producto  $producto
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $producto = Producto::findOrFail($id);
        $producto->delete();
        return redirect()->route('producto.index');
    }
}

TAREA 2/GRUPO6/tarea/resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Producto</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
    @include('navbar')
    <header class="my-5" style="text-align: center">
        <h1 >Productos</h1>
    </header>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-8 m-auto">
                    @yield('content')
                </div>
            </div>
        </div>
    </section>


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

TAREA 2/GRUPO6/tarea/resources/views/navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="{{ route('producto.index') }}">Producto <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

TAREA 2/GRUPO6/tarea/resources/views/productos/create.blade.php
@extends('layout')
@section('content')
                    <form method="POST" action="{{ route('producto.store') }}">
                        @csrf
                        <div class="form-group">
                            <label for="exampleFormControlInput1">Nombre</label>
                            <input name="nombre" type="text" class="form-control" id="exampleFormControlInput1" placeholder="Nombre...">
                        </div>
                        <div class="form-group">
                            <label for="exampleFormControlInput1">Precio</label>
                            <input name="precio" type="number" step="0.1" class="form-control" id="exampleFormControlInput1" placeholder="Nombre...">
                        </div>
                        <div class="form-group">
                            <label for="exampleFormControlTextarea1">Descripcion</label>
                            <textarea name="descripcion" class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Descripcion..."></textarea>
                        </div>
                        <button class="btn btn-primary" type="success">Guardar</button>
                    </form>
                    @endsection

TAREA 2/GRUPO6/tarea/resources/views/productos/edit.blade.php
@extends('layout')
@section('content')
                    <form method="POST" action="{{ route('producto.update', $producto->id) }}">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="exampleFormControlInput1">Nombre</label>
                            <input value="{{ $producto->nombre }}"  name="nombre" type="text" class="form-control" id="exampleFormControlInput1" placeholder="Nombre...">
                        </div>
                        <div class="form-group">
                            <label for="exampleFormControlInput1">Precio</label>
                            <input value="{{ $producto->precio }}" name="precio" type="number" step="0.1" class="form-control" id="exampleFormControlInput1" placeholder="Nombre...">
                        </div>
                        <div class="form-group">
                            <label for="exampleFormControlTextarea1">Descripcion</label>
                            <textarea name="descripcion" class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Descripcion..."> {{ $producto->descripcion }}</textarea>
                        </div>
                        <button class="btn btn-primary" type="success">Guardar</button>
                    </form>
                    @endsection

TAREA 2/GRUPO6/tarea/resources/views/productos/index.blade.php
@extends('layout')
@section('content')
    
                    <a class="btn btn-success mb-5" href="{{ route('producto.create') }}">Nuevo</a>
                    <table class="table">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Nombre</th>
                                <th scope="col">Precio</th>
                                <th scope="col">Descripcion</th>
                                <th scope="col">opciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($productos as $i => $producto)
                                <tr>
                                    <th scope="row">{{ $i + 1 }}</th>
                                    <td>{{ $producto->nombre }}</td>
                                    <td>{{ $producto->precio }}</td>
                                    <td>{{ $producto->descripcion }}</td>
                                    <td>
                                        <a class="btn btn-warning" href="{{ route('producto.edit', $producto->id) }}">Editar</a>
                                        <form action="{{ route('producto.destroy', $producto->id) }}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-danger">Eliminar</button>
                                        </form>
                                        <a class="btn btn-primary" href="{{ route('producto.show', $producto->id) }}">ver</a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    @endsection

TAREA 2/GRUPO6/tarea/resources/views/productos/show.blade.php
@extends('layout')

@section('content')
<form method="POST" action="{{ route('producto.update', $producto->id) }}">
    @csrf
    @method('PUT')
    <div class="form-group">
        <label for="exampleFormControlInput1">Nombre</label>
        <input readonly value="{{ $producto->nombre }}"  name="nombre" type="text" class="form-control" id="exampleFormControlInput1" placeholder="Nombre...">
    </div>
    <div class="form-group">
        <label for="exampleFormControlInput1">Precio</label>
        <input readonly value="{{ $producto->precio }}" name="precio" type="number" step="0.1" class="form-control" id="exampleFormControlInput1" placeholder="Nombre...">
    </div>
    <div class="form-group">
        <label for="exampleFormControlTextarea1">Descripcion</label>
        <textarea readonly name="descripcion" class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Descripcion..."> {{ $producto->descripcion }}</textarea>
    </div>
</form>
@endsection